target: p2p1 p2p2 p2p3 p2p4 p2p5

p2p1:	tcp_p2p_1.cpp
	g++ tcp_p2p_1.cpp -o p2p1	
p2p2:	tcp_p2p_2.cpp
	g++ tcp_p2p_2.cpp -o p2p2
p2p3:	tcp_p2p_3.cpp
	g++ tcp_p2p_3.cpp -o p2p3
p2p4:	tcp_p2p_4.cpp
	g++ tcp_p2p_4.cpp -o p2p4
p2p5:	tcp_p2p_5.cpp
	g++ tcp_p2p_5.cpp -o p2p5
	
clean:	
	rm p2p1
	rm p2p2
	rm p2p3
	rm p2p4
	rm p2p5
